artifact_location: /Users/aineshmohan/Library/Mobile Documents/com~apple~CloudDocs/College/MLM
  25/brain_buddies_mlm-25/alt_ml_pipeline_1/runs/mlflow/577922794496675011
creation_time: 1762909550193
experiment_id: '577922794496675011'
last_update_time: 1762909550193
lifecycle_stage: active
name: /Users/aineshmohan/mlm_outputs/alt_pipeline_1/models/individual
