artifact_location: /Users/aineshmohan/Library/Mobile Documents/com~apple~CloudDocs/College/MLM
  25/brain_buddies_mlm-25/alt_ml_pipeline_1/runs/mlflow/0
creation_time: 1762909550191
experiment_id: '0'
last_update_time: 1762909550191
lifecycle_stage: active
name: Default
